///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace 日本語化検証_Git
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the 日本語化検証_GitRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("23973f57-a634-4882-aec3-e15cd190fa0e")]
    public partial class 日本語化検証_GitRepository : RepoGenBaseFolder
    {
        static 日本語化検証_GitRepository instance = new 日本語化検証_GitRepository();
        日本語化検証_GitRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the 日本語化検証_GitRepository element repository.
        /// </summary>
        [RepositoryFolder("23973f57-a634-4882-aec3-e15cd190fa0e")]
        public static 日本語化検証_GitRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public 日本語化検証_GitRepository() 
            : base("日本語化検証_GitRepository", "/", null, 0, false, "23973f57-a634-4882-aec3-e15cd190fa0e", ".\\RepositoryImages\\日本語化検証_GitRepository23973f57.rximgres")
        {
            _rxmainframe = new 日本語化検証_GitRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("23973f57-a634-4882-aec3-e15cd190fa0e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("5a2a43df-3949-4f64-93aa-685741d0e68f")]
        public virtual 日本語化検証_GitRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class 日本語化検証_GitRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("5a2a43df-3949-4f64-93aa-685741d0e68f")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            日本語化検証_GitRepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "5a2a43df-3949-4f64-93aa-685741d0e68f", "")
            {
                _rxtabintroduction = new 日本語化検証_GitRepositoryFolders.RxTabIntroductionFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5a2a43df-3949-4f64-93aa-685741d0e68f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5a2a43df-3949-4f64-93aa-685741d0e68f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("f8691956-c599-4b67-8fcf-bdae0d14465b")]
            public virtual 日本語化検証_GitRepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("f8691956-c599-4b67-8fcf-bdae0d14465b")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _resetInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "f8691956-c599-4b67-8fcf-bdae0d14465b", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/text[@accessiblename='Enter your name']", "", 30000, null, "3179b4b7-22d6-4290-8adb-03f92ddfebae");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "button[@controlname='btnSubmitUserName']", "", 30000, null, "c751a464-4477-4552-a8a4-caf9beb1f574");
                _resetInfo = new RepoItemInfo(this, "Reset", "link[@controlname='RxLinkBtnReset']/?/?/link[@accessiblename='Reset']", "", 30000, null, "b6eea9f9-96d3-40ff-ab5d-8e1420a0232a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f8691956-c599-4b67-8fcf-bdae0d14465b")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f8691956-c599-4b67-8fcf-bdae0d14465b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("3179b4b7-22d6-4290-8adb-03f92ddfebae")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("3179b4b7-22d6-4290-8adb-03f92ddfebae")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("c751a464-4477-4552-a8a4-caf9beb1f574")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("c751a464-4477-4552-a8a4-caf9beb1f574")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The Reset item.
            /// </summary>
            [RepositoryItem("b6eea9f9-96d3-40ff-ab5d-8e1420a0232a")]
            public virtual Ranorex.Link Reset
            {
                get
                {
                    return _resetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Reset item info.
            /// </summary>
            [RepositoryItemInfo("b6eea9f9-96d3-40ff-ab5d-8e1420a0232a")]
            public virtual RepoItemInfo ResetInfo
            {
                get
                {
                    return _resetInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
